- api/src/main/java/shop/ink3/api/book/book/entity/Book.java
> modify: cart 양방향 매핑 제거

- .github/workflows/ci-cd.yml
> hotfix:DB 환경변수 추가

- .github/workflows/ci-cd.yml
> feat: main 브랜치 ci-cd에 ttb key 추가

- .github/workflows/ci-cd.yml
> feat: dev 브랜치 ci-cd에 ttb_key 추가

- .github/workflows/ci-cd-main.yml
- hotfix: 유레카 url 수정
어떤 변경 사항이 있나요?
> hotfix: 유레카 url 수정

- api/src/main/java/shop/ink3/api/user/point/entity/PointHistory.java
- api/src/main/java/shop/ink3/api/user/point/repository/PointHistoryRepository.java
- api/src/main/java/shop/ink3/api/user/point/service/PointService.java
- 포인트 히스토리에서 사용 내역이 음수로 표시되지 않던 문제 수정
어떤 변경 사항이 있나요?
> hotfix: 사용자 포인트 사용 버그 수정

- api/src/main/java/shop/ink3/api/user/point/service/PointService.java
- 포인트 이력을 가져오는 함수를 호출할때 인자 순서가 잘못 들어가는 코드를 수정
어떤 변경 사항이 있나요?
> hotfix: 포인트 취소시 취소할 포인트 이력을 잘못가져오는 버그 수정

- api/src/main/java/shop/ink3/api/user/like/controller/MeLikeController.java
- MeLikeController에 RequestMapping 잘못되있던 문제 수정
어떤 변경 사항이 있나요?
> hotfix: MeLikeController RequestMapping 잘못되있던 문제 수정

- api/src/main/java/shop/ink3/api/order/order/dto/OrderFormCreateRequest.java
- api/src/main/java/shop/ink3/api/order/orderBook/service/OrderBookService.java
> feat: 주문요청 시 front server와 request 맞게 수정

- api/src/main/java/shop/ink3/api/payment/dto/TossPaymentResponse.java
> hotfix: tossResponse에 JsonIngoreProperty설정으로 예상 외 필드 무시

- api/src/main/java/shop/ink3/api/payment/dto/TossPaymentResponse.java
- api/src/main/java/shop/ink3/api/payment/service/PaymentService.java
> hotfix: payment저장 에러 수정

- api/src/main/java/shop/ink3/api/user/admin/controller/AdminController.java
- api/src/main/java/shop/ink3/api/user/social/dto/SocialUserResponse.java
- api/src/main/java/shop/ink3/api/user/social/entity/Social.java
- api/src/main/java/shop/ink3/api/user/social/repository/SocialRepository.java
- api/src/main/java/shop/ink3/api/user/user/controller/UserController.java
- api/src/main/java/shop/ink3/api/user/user/dto/SocialUserCreateRequest.java
- api/src/main/java/shop/ink3/api/user/user/service/UserService.java
- api/src/test/java/shop/ink3/api/user/admin/controller/AdminControllerTest.java
- api/src/test/java/shop/ink3/api/user/user/controller/UserControllerTest.java
- url 경로 매핑 수정 및 소셜 유저 dto 추가
어떤 변경 사항이 있나요?
> refactor: url 경로 매핑 수정 및 소셜 유저 dto 추가

- api/src/main/java/shop/ink3/api/ApiApplication.java
- api/src/main/java/shop/ink3/api/order/order/controller/OrderController.java
- api/src/main/java/shop/ink3/api/order/order/entity/OrderStatus.java
- api/src/main/java/shop/ink3/api/order/order/repository/OrderRepository.java
- api/src/main/java/shop/ink3/api/order/order/service/OrderMainService.java
- api/src/main/java/shop/ink3/api/order/order/service/OrderService.java
- api/src/main/java/shop/ink3/api/order/orderBook/service/OrderBookService.java
- api/src/main/java/shop/ink3/api/order/orderPoint/exception/OrderPointNotFoundException.java
- api/src/main/java/shop/ink3/api/order/orderPoint/repository/OrderPointRepository.java
- api/src/main/java/shop/ink3/api/order/orderPoint/service/OrderPointService.java
- api/src/main/java/shop/ink3/api/order/refund/controller/RefundController.java
- api/src/main/java/shop/ink3/api/order/refund/dto/RefundCreateRequest.java
- api/src/main/java/shop/ink3/api/order/refund/dto/RefundResponse.java
- api/src/main/java/shop/ink3/api/order/refund/entity/Refund.java
- api/src/main/java/shop/ink3/api/order/refund/service/RefundService.java
- api/src/main/java/shop/ink3/api/order/refundPolicy/dto/RefundPolicyResponse.java
- api/src/main/java/shop/ink3/api/order/refundPolicy/service/RefundPolicyService.java
- api/src/main/java/shop/ink3/api/payment/controller/PaymentController.java
- api/src/main/java/shop/ink3/api/payment/service/PaymentService.java
- api/src/main/java/shop/ink3/api/user/point/eventListener/PointEventListener.java
- api/src/main/java/shop/ink3/api/user/point/eventListener/PointHistoryAfterCancelPaymentEven.java
- api/src/main/java/shop/ink3/api/user/point/service/PointService.java
- api/src/main/resources/application-test.yml
- api/src/test/java/shop/ink3/api/order/refund/controller/RefundControllerTest.java
- api/src/test/java/shop/ink3/api/order/refund/service/RefundServiceTest.java
- api/src/test/java/shop/ink3/api/user/point/controller/PointControllerTest.java
> feat: 반품 처리 로직 수정 (관리자가 승인한 뒤 환불 되도록)

- api/src/main/java/shop/ink3/api/book/book/controller/BookController.java
- api/src/main/java/shop/ink3/api/book/book/dto/BookResponse.java
- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- api/src/main/java/shop/ink3/api/book/category/repository/CategoryRepository.java
> feat:api 기능 추가

- api/src/main/java/shop/ink3/api/order/refund/controller/RefundController.java
- api/src/main/java/shop/ink3/api/order/refund/dto/RefundResponse.java
- api/src/test/java/shop/ink3/api/order/refund/controller/RefundControllerTest.java
- api/src/test/java/shop/ink3/api/order/refund/service/RefundServiceTest.java
> hotfix: 반품 시 userId 미반영 에러 수정

- .github/workflows/ci-cd-dev.yml
- .github/workflows/ci-cd-main.yml
- .github/workflows/ci-cd-pr-test.yml
- api/src/main/java/shop/ink3/api/common/util/PresignUrlPrefixUtil.java
- api/src/main/java/shop/ink3/api/review/review/service/ReviewService.java
- api/src/main/resources/application-test.yml
- minio reverse proxy를 위한 PrefixUtil 클래스 구현
어떤 변경 사항이 있나요?
> hotfix: minio reverse proxy를 위한 PrefixUtil 클래스 구현

- api/src/main/java/shop/ink3/api/common/util/PresignUrlPrefixUtil.java
- api/src/main/java/shop/ink3/api/review/review/service/ReviewService.java
- api/src/test/java/shop/ink3/api/review/review/service/ReviewServiceTest.java
- PresignUrlPrefixUtil 클래스 수정
어떤 변경 사항이 있나요?
> hotfix: PresignUrlPrefixUtil 클래스 수정

- api/src/main/java/shop/ink3/api/common/util/PresignUrlPrefixUtil.java
- api/src/main/java/shop/ink3/api/review/review/service/ReviewService.java
- dev 환경에서는 dev가 붙도록 PrefixUrlUtil 수정
어떤 변경 사항이 있나요?
> hotfix: dev 환경에서는 dev가 붙도록 수정

- api/src/main/java/shop/ink3/api/user/point/policy/exception/CannotDeleteActivePointPolicyException.java
- api/src/main/java/shop/ink3/api/user/point/policy/service/PointPolicyService.java
- 활성화된 맴버십을 삭제할 수 없도록 수정
어떤 변경 사항이 있나요?
> hotfix: 활성화된 맴버십을 삭제할 수 없도록 수정

- api/src/main/java/shop/ink3/api/book/book/dto/MainBookResponse.java
- api/src/main/java/shop/ink3/api/coupon/policy/entity/CouponPolicy.java
- api/src/main/java/shop/ink3/api/coupon/store/dto/CouponStoreDto.java
- api/src/main/java/shop/ink3/api/coupon/store/service/CouponStoreService.java
- api/src/main/java/shop/ink3/api/order/cart/controller/MeCartController.java
- api/src/main/java/shop/ink3/api/order/cart/service/CartService.java
- api/src/main/java/shop/ink3/api/order/order/service/OrderMainService.java
- api/src/main/java/shop/ink3/api/order/orderBook/service/OrderBookService.java
- api/src/main/java/shop/ink3/api/payment/service/PaymentService.java
- api/src/test/java/shop/ink3/api/book/book/controller/BookControllerTest.java
- api/src/test/java/shop/ink3/api/coupon/store/controller/CouponStoreControllerTest.java
- api/src/test/java/shop/ink3/api/coupon/store/service/CouponStoreServiceTest.java
> feat: 쿠폰 적용 및 주문서 보완, 포장지 유무 적용

- api/src/main/java/shop/ink3/api/common/advice/GlobalExceptionHandler.java
- api/src/main/java/shop/ink3/api/order/order/dto/OrderResponse.java
- api/src/main/java/shop/ink3/api/order/orderBook/service/OrderBookService.java
- api/src/main/java/shop/ink3/api/payment/controller/PaymentController.java
- api/src/main/java/shop/ink3/api/payment/dto/ZeroPaymentRequest.java
- api/src/main/java/shop/ink3/api/payment/entity/PaymentType.java
- api/src/main/java/shop/ink3/api/payment/service/PaymentService.java
> hotfix: 0원 결제에 대한 로직 추가

- api/src/main/java/shop/ink3/api/coupon/store/controller/CouponStoreController.java
- api/src/main/java/shop/ink3/api/order/order/controller/OrderController.java
- api/src/main/java/shop/ink3/api/order/order/dto/OrderDetailsResponse.java
- api/src/main/java/shop/ink3/api/order/order/dto/OrderResponse.java
- api/src/main/java/shop/ink3/api/order/order/entity/OrderStatus.java
- api/src/main/java/shop/ink3/api/order/order/repository/OrderRepository.java
- api/src/test/java/shop/ink3/api/coupon/store/controller/CouponStoreControllerTest.java
> feat: 관리자 배송 상태 변경 및 바로 구매 로직 추가

- api/src/main/java/shop/ink3/api/LogoController.java
- api/src/main/java/shop/ink3/api/review/review/dto/ReviewPointType.java
- api/src/main/java/shop/ink3/api/review/review/dto/ReviewResponse.java
- api/src/main/java/shop/ink3/api/review/review/service/ReviewService.java
- api/src/main/resources/application-test.yml
- api/src/test/java/shop/ink3/api/review/review/controller/MeReviewControllerTest.java
- api/src/test/java/shop/ink3/api/review/review/service/ReviewServiceTest.java
> feat: 리뷰 포인트 연결

- api/src/main/java/shop/ink3/api/book/book/controller/BookController.java
- api/src/main/java/shop/ink3/api/book/book/dto/BookResponse.java
- api/src/main/java/shop/ink3/api/book/book/dto/MainBookResponse.java
- api/src/main/java/shop/ink3/api/book/book/enums/SortType.java
- api/src/main/java/shop/ink3/api/book/book/repository/BookQuerydslRepository.java
- api/src/main/java/shop/ink3/api/book/book/repository/BookQuerydslRepositoryImpl.java
- api/src/main/java/shop/ink3/api/book/book/repository/BookRepository.java
- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- api/src/main/java/shop/ink3/api/review/review/repository/ReviewRepository.java
- api/src/main/java/shop/ink3/api/user/like/repository/LikeRepository.java
- api/src/test/java/shop/ink3/api/book/book/controller/BookControllerTest.java
- api/src/test/java/shop/ink3/api/book/book/service/BookServiceTest.java
- 도서 목록 페이지 정렬 및 찜/리뷰 개수 구현
- 도서 상세 페이지 찜 연결
어떤 변경 사항이 있나요?
> feat: 도서 목록 페이지 정렬 및 찜/리뷰 개수 구현 & 도서 상세 페이지 찜 연결

- api/src/main/java/shop/ink3/api/review/review/service/ReviewService.java
- api/src/main/java/shop/ink3/api/user/point/policy/dto/PointPolicyCreateRequest.java
- api/src/main/java/shop/ink3/api/user/point/policy/dto/PointPolicyResponse.java
- api/src/main/java/shop/ink3/api/user/point/policy/dto/PointPolicyUpdateRequest.java
- api/src/main/java/shop/ink3/api/user/point/policy/entity/PointPolicy.java
- api/src/main/java/shop/ink3/api/user/point/policy/service/PointPolicyService.java
- api/src/test/java/shop/ink3/api/order/cart/repository/CartRepositoryTest.java
- api/src/test/java/shop/ink3/api/review/review/service/ReviewServiceTest.java
- 리뷰 포인트 -> PointPolicy에서 포인트 가져오도록 수정
어떤 변경 사항이 있나요?
> hotfix: 리뷰 포인트 수정

- api/src/main/java/shop/ink3/api/coupon/store/controller/MeCouponStoreController.java
- api/src/main/java/shop/ink3/api/coupon/store/dto/CouponStoreResponse.java
- api/src/main/java/shop/ink3/api/coupon/store/repository/CouponStoreQuerydslRepository.java
- api/src/main/java/shop/ink3/api/coupon/store/repository/CouponStoreQuerydslRepositoryImpl.java
- api/src/main/java/shop/ink3/api/coupon/store/repository/CouponStoreRepository.java
- api/src/main/java/shop/ink3/api/coupon/store/service/CouponStoreService.java
- 쿠폰함 조회 수정 및 QuerydslRepository 구현
어떤 변경 사항이 있나요?
> hotfix: 쿠폰함 조회 수정 및 QuerydslRepository 구현

- api/src/main/java/shop/ink3/api/book/book/external/aladin/client/AladinClientImpl.java
- api/src/main/java/shop/ink3/api/book/book/external/aladin/controller/AladinController.java
- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- 알라딘 api를 사용한 도서 등록 기능을 위해 코드 일부 수정
어떤 변경 사항이 있나요?
> hotfix: 알라딘 api를 사용한 도서 등록 기능을 위해 코드 일부 수정

- api/src/main/java/shop/ink3/api/book/book/dto/MainBookResponse.java
- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- 메인페이지 도서 이미지 출력
어떤 변경 사항이 있나요?
> feat: 메인페이지 도서 이미지 출력

- api/src/main/java/shop/ink3/api/coupon/store/dto/CouponStoreDto.java
- api/src/main/java/shop/ink3/api/coupon/store/dto/CouponStoreResponse.java
- api/src/main/java/shop/ink3/api/coupon/store/service/CouponStoreService.java
- api/src/test/java/shop/ink3/api/coupon/store/service/CouponStoreServiceTest.java
> feat: 쿠폰 조회 수정

- api/src/main/java/shop/ink3/api/user/point/history/eventListener/PointEventListener.java
- 멤버십별 포인트 적립 구현
어떤 변경 사항이 있나요?
> feat: 멤버십별 포인트 적립 구현

- api/src/main/java/shop/ink3/api/user/point/policy/entity/PointPolicy.java
- api/src/main/java/shop/ink3/api/user/point/policy/service/PointPolicyService.java
- 포인트 정책 수정에 이미지 리뷰 포인트 추가
어떤 변경 사항이 있나요?
> hotfix: 포인트 정책 수정에 이미지 리뷰 포인트 추가

- api/src/main/java/shop/ink3/api/order/cart/controller/MeCartController.java
- api/src/main/java/shop/ink3/api/order/cart/repository/CartRepository.java
- api/src/main/java/shop/ink3/api/order/cart/service/CartService.java
- 장바구니에서 선택된 상품만 주문하도록 수정
어떤 변경 사항이 있나요?
> hotfix: 장바구니에서 선택된 상품만 주문하도록 수정

- api/src/main/java/shop/ink3/api/coupon/categoryCoupon/entity/CategoryCouponService.java
- api/src/main/java/shop/ink3/api/coupon/coupon/controller/CouponController.java
- api/src/main/java/shop/ink3/api/coupon/coupon/service/Impl/CouponServiceImpl.java
- api/src/main/java/shop/ink3/api/coupon/store/controller/CouponStoreController.java
- api/src/test/java/shop/ink3/api/coupon/store/controller/CouponStoreControllerTest.java
> feat: 부모카테고리 쿠폰 조회 api 추가

- api/src/main/java/shop/ink3/api/ApiApplication.java
- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- api/src/main/java/shop/ink3/api/book/category/controller/CategoryController.java
- api/src/main/java/shop/ink3/api/book/category/service/CategoryService.java
- api/src/main/java/shop/ink3/api/common/config/CacheConfig.java
> feat: cache 적용

- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- api/src/main/java/shop/ink3/api/book/category/service/CategoryService.java
- pom.xml
> hotfix: 캐시 버그 수정

- api/src/main/java/shop/ink3/api/book/book/dto/BookDetailResponse.java
- api/src/main/java/shop/ink3/api/book/book/dto/BookPreviewResponse.java
- api/src/main/java/shop/ink3/api/book/book/entity/Book.java
- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- api/src/main/java/shop/ink3/api/elastic/service/BookSearchService.java
- book api 성능 개선
어떤 변경 사항이 있나요?
> rafactor: book api 성능 개선

- api/src/main/java/shop/ink3/api/review/review/controller/ReviewController.java
- api/src/main/java/shop/ink3/api/review/review/dto/ReviewUpdateRequest.java
- api/src/test/java/shop/ink3/api/review/review/controller/ReviewControllerTest.java
- api/src/test/java/shop/ink3/api/user/like/controller/LikeControllerTest.java
- api/src/test/java/shop/ink3/api/user/like/controller/MeLikeControllerTest.java
- api/src/test/java/shop/ink3/api/user/like/service/LikeServiceTest.java
- api/src/test/java/shop/ink3/api/user/point/policy/controller/PointPolicyControllerTest.java
- api/src/test/java/shop/ink3/api/user/point/policy/service/PointPolicyServiceTest.java
- Point 정책 관련 테스트 추가
- Like 관련 테스트코드 추가
- ReviewControllerTest 구현
어떤 변경 사항이 있나요?
> test: 미구현 테스트코드 추가

- api/src/main/java/shop/ink3/api/book/book/entity/Book.java
- api/src/main/java/shop/ink3/api/elastic/service/BookSearchService.java
- api/src/main/java/shop/ink3/api/review/review/repository/ReviewRepository.java
- api/src/main/java/shop/ink3/api/review/review/service/ReviewService.java
- api/src/main/java/shop/ink3/api/user/like/service/LikeService.java
- api/src/test/java/shop/ink3/api/review/review/service/ReviewServiceTest.java
- book의 평점, 리뷰 개수를 review, like에서 update 하도록 수정
어떤 변경 사항이 있나요?
> hotfix: book의 평점, 리뷰 개수를 review, like에서 update 하도록 수정

- api/src/main/java/shop/ink3/api/book/book/service/BookService.java
- api/src/main/java/shop/ink3/api/book/category/exception/CategoryHierarchyCycleException.java
- api/src/main/java/shop/ink3/api/book/category/exception/SelfParentingCategoryException.java
- api/src/main/java/shop/ink3/api/book/category/service/CategoryService.java
- api/src/main/java/shop/ink3/api/common/advice/GlobalExceptionHandler.java
- elastic/index.json
- 엘라스틱 서치 매핑 수정
- 카테고리 버그 수정
어떤 변경 사항이 있나요?
> hotfix: 카테고리 버그 수정 및 엘라스틱 매핑 수정

- api/src/main/java/shop/ink3/api/order/cart/service/CartService.java
- api/src/main/java/shop/ink3/api/review/review/controller/MeReviewController.java
- api/src/test/java/shop/ink3/api/coupon/store/controller/MeCouponStoreControllerTest.java
- api/src/test/java/shop/ink3/api/review/review/controller/MeReviewControllerTest.java
- 테스트코드 수정
- 리뷰 등록 시 200 반환
어떤 변경 사항이 있나요?
> hotfix: 테스트코드 수정 및 리뷰 등록 시 200 반환

- api/src/main/java/shop/ink3/api/order/guest/controller/GuestOrderController.java
- api/src/main/java/shop/ink3/api/order/guest/dto/GuestOrderCreateRequest.java
- api/src/main/java/shop/ink3/api/order/order/exception/InsufficientBookStockException.java
- api/src/main/java/shop/ink3/api/order/order/repository/OrderRepository.java
- api/src/main/java/shop/ink3/api/order/orderBook/dto/OrderBookUpdateRequest.java
> hotfix: 소나큐브 이슈 해결

- api/src/main/java/shop/ink3/api/order/cart/service/CartService.java
- api/src/main/java/shop/ink3/api/review/review/controller/MeReviewController.java
- api/src/test/java/shop/ink3/api/review/review/controller/MeReviewControllerTest.java
- 장바구니 조회 시 presignUrl 붙여지도록 수정
- 리뷰 등록 시 응답 코드 수정
어떤 변경 사항이 있나요?
> hotfix: 장바구니 조회 시 presignUrl 붙여지도록 수정 및 리뷰 등록 시 응답 코드 수정

- api/src/main/java/shop/ink3/api/coupon/categoryCoupon/entity/CategoryCouponService.java
- api/src/test/java/shop/ink3/api/coupon/categoryCoupon/entity/CategoryCouponServiceTest.java
- api/src/test/java/shop/ink3/api/coupon/coupon/service/CouponServiceTest.java
- api/src/test/java/shop/ink3/api/coupon/policy/controller/CouponPolicyControllerTest.java
- api/src/test/java/shop/ink3/api/coupon/policy/service/CouponPolicyServiceTest.java
- api/src/test/java/shop/ink3/api/coupon/store/controller/MeCouponStoreControllerTest.java
- api/src/test/java/shop/ink3/api/coupon/store/service/CouponStoreServiceTest.java
- api/src/test/java/shop/ink3/api/payment/controller/PaymentControllerTest.java
> test: 쿠폰 테스트 추가 구현

- api/src/main/java/shop/ink3/api/order/cart/controller/MeCartController.java
- api/src/main/java/shop/ink3/api/order/cart/service/CartService.java
- api/src/test/java/shop/ink3/api/book/category/controller/CategoryControllerTest.java
- api/src/test/java/shop/ink3/api/coupon/categoryCoupon/entity/CategoryCouponServiceTest.java
- api/src/test/java/shop/ink3/api/coupon/coupon/service/CouponServiceTest.java
- api/src/test/java/shop/ink3/api/coupon/store/service/CouponStoreServiceTest.java
- api/src/test/java/shop/ink3/api/order/cart/service/CartServiceTest.java
> test: 부족한 테스트 케이스 추가 구현

- api/src/test/java/shop/ink3/api/payment/paymentUtil/parser/impl/PointPaymentParserTest.java
- api/src/test/java/shop/ink3/api/payment/paymentUtil/parser/impl/TossPaymentParserTest.java
- api/src/test/java/shop/ink3/api/payment/paymentUtil/processor/impl/PointPaymentProcessorTest.java
- api/src/test/java/shop/ink3/api/payment/paymentUtil/processor/impl/TossPaymentProcessorTest.java
> test: payment테스트 추가

- api/src/test/java/shop/ink3/api/book/book/controller/BookControllerTest.java
- api/src/test/java/shop/ink3/api/book/book/service/BookServiceTest.java
- api/src/test/java/shop/ink3/api/order/guest/controller/GuestPaymentControllerTest.java
- api/src/test/java/shop/ink3/api/order/guest/service/GuestOrderMainServiceTest.java
- api/src/test/java/shop/ink3/api/order/order/service/OrderMainServiceTest.java
- api/src/test/java/shop/ink3/api/order/orderPoint/service/OrderPointServiceTest.java
- api/src/test/java/shop/ink3/api/order/shipment/service/AutoShipmentServiceTest.java
> test: 부족한 테스트케이스 추가
